DELIMITER /
CREATE TRIGGER ID_AUTO_INCREMENT_ANSWERDATE
BEFORE INSERT ON ANSWERDATE
FOR EACH ROW 
BEGIN
    IF NEW.uselessid IS NULL THEN
        SET NEW.uselessId = LAST_INSERT_ID() + 1;
    END IF;
END; /
DELIMITER ;


DELIMITER /
CREATE TRIGGER ID_AUTO_INCREMENT_ANSWERLIST
BEFORE INSERT ON ANSWERLIST
FOR EACH ROW 
BEGIN
    IF NEW.uselessid IS NULL THEN
        SET NEW.uselessId = LAST_INSERT_ID() + 1;
    END IF;
END; /
DELIMITER ;


DELIMITER /
CREATE TRIGGER ID_AUTO_INCREMENT_ANSWERTEXT
BEFORE INSERT ON ANSWERTEXT
FOR EACH ROW 
BEGIN
    IF NEW.uselessid IS NULL THEN
        SET NEW.uselessId = LAST_INSERT_ID() + 1;
    END IF;
END; /
DELIMITER ;
